drop table conference if exists;

create table conference (
        id bigint generated by default as identity (start with 1),
        description varchar(255) not null,
        ended_date timestamp not null,
        name varchar(255) not null,
        slug varchar(255) not null,
        started_date timestamp not null,
        version integer,
        primary key (id)
    );

insert 
    into
        conference
        ( name, slug, description, started_date, ended_date, version) 
    values
        ( 'JUD2013', 'jud-2013', 'SpringOne Conference 2013: USA', '2012-06-23 00:00:00', '2012-06-29 00:00:00',  1);
